blog/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from . import views

urlpatterns = [
    path("", views.blog_index, name="blog_index"),
    path("<int:id>/", views.blog_detail, name="blog_detail")
  

]

cec_portfolio/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name='home'),
    path('contact/', views.contact, name = 'contact'),

    # authentification
    path('accounts/', include('django.contrib.auth.urls')),

    # apps
    path('projects/', include('projects.urls')), 
    path('blog/', include('blog.urls'))

]

projects/urls.py
from django.urls import path
from django.contrib import admin 
from . import views

urlpatterns = [
    path("", views.project_index, name="project_index"),
    path("<int:pk>/", views.project_detail, name="project_detail"),

# A renommer    
    path("add/", views.project_add, name="add"),
    path('show', views.show, name='show'),
    path("update/<int:id>", views.update, name="update"),
    path('delete/<int:id>', views.delete, name ="delete")
]

blog/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    published = models.BooleanField(default=False)    
    categories = models.ManyToManyField('Category', related_name='posts')
    def __str__(self):
        return self.name

cec_portfolio/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# class UserProfileInfo(models.Model):
#     user = models.OneToOneField(User,on_delete=models.CASCADE)
#     portfolio_site = models.URLField(blank=True)
#     profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

#     def __str__(self):
#         return self.user.username

projects/models.py
from django.db import models

# Create your models here.
# A déplacer
class Technology(models.Model):
    name = models.CharField(max_length=100, unique=True)
    
    def __str__(self):
        return self.name

class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    # image = models.FilePathField(path='projects/static/img/')  
    image = models.ImageField(upload_to='projects/static/img', null=True, blank=True) 
    repo_url = models.URLField(blank=False)
    website_url = models.URLField(blank=True)
    date = models.DateTimeField(auto_now_add=True)
    # technology = models.ManyToManyField(Technology, related_name='projects', blank=True)

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from blog.models import Post 
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('title','content','created_on','published','categories')

cec_portfolio/forms.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
    
class UserProf(forms.ModelForm):
        class Meta:
            model = User
            fields = '__all__'

projects/forms.py
from django import forms
from . import models
from projects.models import Project

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = [ 
            "name", 
            "description", 
            "image",
            "repo_url",
            "website_url",
        ] 



     

blog/views.py
from django.shortcuts import render
from blog.models import Post

# Create your views here.

# Add post in Blog
# def add_post(request, pk):
#     form = PostForm()
#     if request.method == 'POST':
#         if form_is_valid():
#             post= Post(
#                 title = form.clean_data["title"],
#                 content = form.clean_data["content"],
#                 created_on = form.clean_data["created_on"],
#                 published = form.clean_data["published"],
#                 categories = form.clean_data["categories"]
#             )

# ReadAllPosts
def blog_index(request):
    posts = Post.objects.all().order_by('-created_on')
    context = {
        "posts" : posts,
    }
    return render(request, "blog_index.html", context)

def blog_category(request, category):
    posts = Post.objects.filter(
        categories__name__contains=category
    ).order_by(
        '-created_on'
    )
    context = {
        "category": category,
        "posts": posts
    }
    return render(request, "blog_category.html", context)

def blog_detail(request, id):
    post = Post.objects.get(id=id)
    context = {
        "posts":post,
    }

    return render(request, "blog_details.html", context)    

cec_portfolio/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect 
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout as django_logout
from django.contrib.auth.models import User

# Méthode / afficher Home.
def home(request):   
    return render(request, "home.html")


# # Méthode / afficher Projets.
# def projects(request):
#     return render(request, "projects.html")

# Méthode / afficher Articles.
def articles(request):
    return render(request, "articles.html")

# Méthode / afficher Formulaire de message Contact.
def contact(request):
    return render(request, "contact.html")

# def login(request):
#     return render(request, "login.html")
    
# def loginSubmit(request):
#     if request.method == 'POST':
#         email=request.POST.get('email')
#         password = request.POST.get("password")
#         try:
#           user = authenticate(username=username, password=password)
#         except:
#             message = "Identifiant et/ou mot de passe invalides."
#         return render(request,"login.html",{"msg":message})
#         print(user)
#     request.session['auth'] = True
#     request.session['user'] = email
#     return redirect("/")

# def register(request):
#     registered = False
#     if request.method == 'POST':
#         user_form = UserForm(data=request.POST)
#         if user_form.is_valid():
#             user = user_form.save()
#             user.set_password(user.password)
#             user.save()
#             registered = True
#         else:
#             print(user_form.errors)
#     else:
#         user_form = UserForm()
#     return render(request,'/register.html',
#                           {'user_form':user_form,
#                            'registered':registered})    

# def register(request):
#     return render(request, "register.html")

# def registerSubmit(request):
#     return render()                        

projects/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from projects.models import Project
from projects.forms import ProjectForm
from django.contrib.auth.decorators import login_required

# Create your views here.

# Méthode pour afficher l'index de tous les projets
def project_index(request):
    projects = Project.objects.all()
    context = {
        'projects' : projects
    }
    return render(request, 'project_index.html', context)

# Méthode pour afficher le projet sélectionné 
def project_detail(request, id):
    project = Project.objects.get(id=id)
    context = {
        'project': project
    }
    return render(request, 'project_detail.html', context) 

# Methode pour ajouter un projet 
 
def project_add(request): 
    context ={} 

    form = ProjectForm(request.POST or None) 
    if form.is_valid(): 
        form.save()
        return redirect("/projects/show")  
          
    context['form']= form
    
    return render(request, "project_add.html", context) 

# Méthode pour accéder à tout le CRUD version admin  [test]
def show(request):
    projects = Project.objects.all()
    return render(request, 'show.html', {'projects': projects})

# Méthode pour mettre à jour un projet
def update(request, id):
    project = Project.objects.get(id=id) 
    form = ProjectForm(request.POST, instance=project)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render (request, 'project_update.html', {'project': project})

# Méthode pour supprimer un projet
def delete(request, id):
    project = Project.objects.get(id=id)
    project.delete()
    return redirect("/projects/")        

cec_portfolio/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- mettre lien CSS -->
    <link href="{{ STATIC_URL }}css/app.css" rel="stylesheet" media="screen">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}
    {% endblock %}
</head>

<body>
    <br>
    <div class="container">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">

                        <li><a href="/">Home</a></li>
                        <li><a href="/projects">Projets</a></li>
                        <li><a href="/blog">Blog</a></li>

                    </ul>
                    {% if request.session.auth == True %}
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/logout">Se déconnecter</a></li>
                    </ul>
                    {% else %}
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/contact">Contact</a></li>
                        <li><a href="/login">Se connecter</a></li>
                    </ul>
                    {% endif %}
                </div>
                <!--/.nav-collapse -->
            </div>
            <!--/.container-fluid -->
        </nav>
    </div>
    {% block page_content %}
    {% endblock %}
</body>

<footer>

</footer>

</html>

cec_portfolio/templates/contact.html
{% extends 'base.html' %}

{% block head %}
    <title>Contact</title>
{% endblock %}

{% block page_content %}
    
    <div class="container">
        <h1>Restons en contact</h1>
        <h2>Laissez moi un message</h2>
        
    </div>
    
{% endblock %}

cec_portfolio/templates/home.html
{% extends 'base.html' %}

{% block head %}
    <title>Accueil</title>
{% endblock %}

{% block page_content %}
    
    <div class="container">
        <h1>Une</h1>
        <h2>Bienvenue sur mon portfolio</h2>
        
    </div>
    
{% endblock %}

projects/templates/project_add.html
{% extends "base.html" %}
{% load static %}
{% block page_content %}

<container>
    <h1>Ajouter un projet</h1>
    <form method="POST" enctype="multipart/form-data"> 
        {% csrf_token %}
         
        {{ form.as_p }} 
          
        <input type="submit" value="Ajouter"> 
    </form> 
</container>

{% endblock %}

projects/templates/project_detail.html
{% extends "base.html" %}
{% load static %}
{% block head %}
    <title>Zoom sur</title>
{% endblock %}
{% block page_content %}

<div class="container">
    <h1>{{ project.name }}</h1>
    <div class="row">
        <div class="col-md-8">
            <img src="{% static project.image.url %}" alt="" width="100%">
        </div>
        <div class="col-md-4">
            <h5>Le projet en bref :</h5>
            <p>{{ project.description }}</p>
            <br>
            <h5>Technologies utilisées:</h5>
            <p>{{ project.technology }}</p>
        </div>
    </div>
</div>
{% endblock %}

projects/templates/project_index.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<title>Projets</title>
{% endblock %}

{% block page_content %}
<div class="container">
    <h1>Mes Projets</h1>

    <div class="row">
        {% for project in projects %}
        <div class="col-md-4">
            <div class="card mb-2">
                <img class="card-img-top" src="{% static project.image.url %}">
                <div class="card-body">
                    <h5 class="card-title">{{ project.name }}</h5>
                    <p class="card-text">{{ project.description }}</p>
                    <a href="{% url 'project_detail' project.pk %}" class="btn btn-primary">
                        En savoir plus
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

projects/templates/project_update.html
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% extends "base.html" %}
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>
{% block page_content %}

<body>
    <form method="POST" class="post-form" action="/update/{{project.id}}">
        {% csrf_token %}
        <div class="container">
            <br>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>{{project.name}}</h3>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label"></label>
                <div class="col-sm-4">
                    <input type="hidden" name="eid" id="id_eid" required maxlength="20" value="{{ project.id }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Nom du projet :</label>
                <div class="col-sm-4">
                    <input type="text" name="name" id="id_name" required maxlength="100"
                        value="{{ project.name }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Description :</label>
                <div class="col-sm-4">
                    <input type="text" name="description" id="id_description" required maxlength="254"
                        value="{{ project.description }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Image:</label>
                <div class="col-sm-4">
                    <input type="image" name="image" id="id_image"
                        value="{{ project.image }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-success">Mettre à jour</button>
                </div>
            </div>
        </div>
    </form>
</body>

</html>

{% endblock %}

projects/templates/show.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Nouveau Projet</title>
    {% extends "base.html" %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    {% block page_content %}

</head>

<body>
    <table class="table table-striped table-bordered table-sm">
        <thead class="thead-dark">
            <tr>
                <th>Projet ID</th>
                <th>Nom du projet</th>
                <th>Description du projet</th>
                <th>Image</th>
                <th>Url du projet</th>
                <th>Repot Gitlab du projet</th>
                <!-- <th>Date</th>
                <th>Category id</th> -->
            </tr>
        </thead>
        <tbody>
            {% for project in projects %}
            <tr>
                <td>{{ project.id }}</td>
                <td>{{ project.name }}</td>
                <td>{{ project.description }}</td>
                <td>{{ project.image}}</td>
                <td>{{ project.repo_url}}</td>
                <td>{{ project.website_url}}</td>
                <!-- <td>{{ project.date}}</td> -->
                <!-- <td>{{ project.category.id}}</td> -->

                <td>
                    <a href="{% url 'update' project.id %}"><span class="glyphicon glyphicon-pencil">Editer</span></a>
                    <a href="{% url 'delete' project.id %}">Supprimer</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <br>
    <br>
    <center><a href="{% url 'add'%}" class="btn btn-primary">Ajouter un projet</a></center>
</body>

</html>
{% endblock %}